---
version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PW}
      POSTGRES_HOST: ${PG_HOST}
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/datass
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - etl_network
  etl:
    container_name: etl
    build:
      context: ./etl
      args:
        PG_DB: ${PG_DB}
        PG_USER: ${PG_USER}
        PG_HOST: ${PG_HOST}
        PG_PW: ${PG_PW}
        REPO: ${REPO}
    depends_on:
      - db
    networks:
      - etl_network

networks:
  etl_network: null
